// ===== PERMISSIONS DEFINITION =====
export const PERMISSIONS = {
  MANAGE_ROLES: 1 << 0,
  VIEW_ANALYTICS: 1 << 1,
  MANAGE_SETTINGS: 1 << 2,
  USER: {
    CREATE: 1 << 3,
    READ: 1 << 4,
    UPDATE: 1 << 5,
    DELETE: 1 << 6,
  },
  POST: {
    CREATE: 1 << 7,
    READ: 1 << 8,
    UPDATE: 1 << 9,
    DELETE: 1 << 10,
  },
  COMMENT: {
    CREATE: 1 << 11,
    READ: 1 << 12,
    UPDATE: 1 << 13,
    DELETE: 1 << 14,
  },
} as const

// ===== ROLES DEFINITION =====
export const ROLES = {
  GUEST: PERMISSIONS.POST.READ | PERMISSIONS.COMMENT.READ,

  USER:
    PERMISSIONS.POST.READ |
    PERMISSIONS.POST.CREATE |
    PERMISSIONS.POST.UPDATE |
    PERMISSIONS.COMMENT.READ |
    PERMISSIONS.COMMENT.CREATE,

  MODERATOR:
    PERMISSIONS.POST.READ |
    PERMISSIONS.POST.CREATE |
    PERMISSIONS.POST.UPDATE |
    PERMISSIONS.POST.DELETE |
    PERMISSIONS.COMMENT.READ |
    PERMISSIONS.COMMENT.CREATE |
    PERMISSIONS.COMMENT.UPDATE |
    PERMISSIONS.COMMENT.DELETE |
    PERMISSIONS.USER.READ,

  ADMIN:
    PERMISSIONS.MANAGE_ROLES |
    PERMISSIONS.VIEW_ANALYTICS |
    PERMISSIONS.MANAGE_SETTINGS |
    PERMISSIONS.USER.CREATE |
    PERMISSIONS.USER.READ |
    PERMISSIONS.USER.UPDATE |
    PERMISSIONS.USER.DELETE |
    PERMISSIONS.POST.CREATE |
    PERMISSIONS.POST.READ |
    PERMISSIONS.POST.UPDATE |
    PERMISSIONS.POST.DELETE |
    PERMISSIONS.COMMENT.CREATE |
    PERMISSIONS.COMMENT.READ |
    PERMISSIONS.COMMENT.UPDATE |
    PERMISSIONS.COMMENT.DELETE,

  SUPER_ADMIN: 0xffffffff,
} as const
