// biome-ignore assist/source/organizeImports: <explanation>
import {
  ClassicEditor as ClassicEditorBase,
  InlineEditor as InlineEditorBase,
  Alignment,
  AutoImage,
  AutoLink,
  BlockQuote,
  Bold,
  Code,
  CodeBlock,
  Essentials,
  FindAndReplace,
  Font,
  GeneralHtmlSupport,
  Heading,
  Highlight,
  HorizontalLine,
  Image,
  ImageCaption,
  ImageInsert,
  ImageResize,
  ImageStyle,
  ImageToolbar,
  ImageUpload,
  Indent,
  IndentBlock,
  Italic,
  Link,
  LinkImage,
  MediaEmbed,
  Mention,
  Paragraph,
  PictureEditing,
  RemoveFormat,
  ShowBlocks,
  SourceEditing,
  SpecialCharacters,
  SpecialCharactersEssentials,
  Strikethrough,
  Subscript,
  Superscript,
  Table,
  TableCaption,
  TableCellProperties,
  TableColumnResize,
  TableProperties,
  TableToolbar,
  Underline,
  List,
  type EditorConfig,
} from 'ckeditor5'

import FlmAdapter from './FlmAdapter'
import SimpleUploadAdapter from './SimpleUploadAdapter'

class ClassicEditor extends ClassicEditorBase {}
class InlineEditor extends InlineEditorBase {}

const plugins = [
  BlockQuote,
  Bold,
  Heading,
  Image,
  ImageCaption,
  ImageStyle,
  ImageToolbar,
  Indent,
  Italic,
  Link,
  MediaEmbed,
  Paragraph,
  Table,
  TableToolbar,
  Alignment,
  AutoImage,
  AutoLink,
  Code,
  CodeBlock,
  Essentials,
  FindAndReplace,
  Font,
  Highlight,
  HorizontalLine,
  ImageInsert,
  ImageResize,
  ImageUpload,
  IndentBlock,
  GeneralHtmlSupport,
  LinkImage,
  Mention,
  PictureEditing,
  RemoveFormat,
  ShowBlocks,
  SourceEditing,
  SpecialCharacters,
  SpecialCharactersEssentials,
  Strikethrough,
  Subscript,
  Superscript,
  TableCaption,
  TableCellProperties,
  TableColumnResize,
  TableProperties,
  Underline,
  List,
  SimpleUploadAdapter,
  FlmAdapter,
]

ClassicEditor.builtinPlugins = plugins
InlineEditor.builtinPlugins = plugins

const config: EditorConfig = {
  licenseKey: 'GPL',
  toolbar: {
    items: [
      'undo',
      'redo',
      '|',
      'showBlocks',
      'findAndReplace',
      'selectAll',
      '|',
      'heading',
      '|',
      'fontSize',
      'fontFamily',
      'fontColor',
      'fontBackgroundColor',
      '-',
      'bold',
      'italic',
      'underline',
      {
        label: 'Formatting',
        icon: 'text',
        items: ['strikethrough', 'subscript', 'superscript', 'code', '|', 'removeFormat'],
      },
      '|',
      'specialCharacters',
      'horizontalLine',
      '|',
      'link',
      'insertImage',
      'flm',
      'insertTable',
      {
        label: 'Insert',
        icon: 'plus',
        items: ['highlight', 'blockQuote', 'mediaEmbed', 'codeBlock'],
      },
      '|',
      'alignment',
      '|',
      'bulletedList',
      'numberedList',
      'outdent',
      'indent',
      '|',
      'sourceEditing',
    ],
    shouldNotGroupWhenFull: true,
  },
  htmlSupport: {
    allow: [
      {
        name: /^.*$/,
        styles: true,
        attributes: true,
        classes: true,
      },
    ],
  },
  fontFamily: {
    supportAllValues: true,
  },
  fontSize: {
    options: [10, 12, 14, 'default', 18, 20, 22],
    supportAllValues: true,
  },
  image: {
    resizeOptions: [
      {
        name: 'resizeImage:original',
        label: 'Default image width',
        value: null,
      },
      {
        name: 'resizeImage:50',
        label: '50% page width',
        value: '50',
      },
      {
        name: 'resizeImage:75',
        label: '75% page width',
        value: '75',
      },
    ],
    toolbar: [
      'imageTextAlternative',
      'toggleImageCaption',
      '|',
      'imageStyle:inline',
      'imageStyle:wrapText',
      'imageStyle:breakText',
      '|',
      'resizeImage',
    ],
  },
  list: {
    properties: {
      styles: true,
      startIndex: true,
      reversed: true,
    },
  },
  link: {
    addTargetToExternalLinks: true,
    defaultProtocol: 'https://',
    decorators: {
      toggleDownloadable: {
        mode: 'manual',
        label: 'Downloadable',
        attributes: {
          download: 'file',
        },
      },
    },
  },
  mention: {
    feeds: [
      {
        marker: '@',
        feed: [
          '@apple',
          '@bears',
          '@brownie',
          '@cake',
          '@cake',
          '@candy',
          '@canes',
          '@chocolate',
          '@cookie',
          '@cotton',
          '@cream',
          '@cupcake',
          '@danish',
          '@donut',
          '@dragée',
          '@fruitcake',
          '@gingerbread',
          '@gummi',
          '@ice',
          '@jelly-o',
          '@liquorice',
          '@macaroon',
          '@marzipan',
          '@oat',
          '@pie',
          '@plum',
          '@pudding',
          '@sesame',
          '@snaps',
          '@soufflé',
          '@sugar',
          '@sweet',
          '@topping',
          '@wafer',
        ],
        minimumCharacters: 1,
      },
    ],
  },
  table: {
    contentToolbar: [
      'tableColumn',
      'tableRow',
      'mergeTableCells',
      'tableProperties',
      'tableCellProperties',
      'toggleTableCaption',
    ],
  },
  simpleUpload: {
    // The URL that the images are uploaded to.
    uploadUrl: '/api/file-manager',

    // // Enable the XMLHttpRequest.withCredentials property.
    withCredentials: true,

    // Headers sent along with the XMLHttpRequest to the upload server.
    headers: {
      // 'X-CSRF-TOKEN': 'CSRF-Token',
      //   Authorization: `Bearer ${Storage.get(constants.ACCESS_TOKEN_KEY)}`,
    },
  },
}

ClassicEditor.defaultConfig = config
InlineEditor.defaultConfig = {
  ...config,
  toolbar: [
    'undo',
    'redo',
    '|',
    'fontColor',
    'fontBackgroundColor',
    {
      label: 'Formatting',
      icon: 'text',
      items: ['bold', 'italic', 'underline', 'strikethrough', 'subscript', 'superscript', 'code', '|', 'removeFormat'],
    },
    '|',
    'specialCharacters',
    'horizontalLine',
    '|',
    'link',
    'insertImage',
    'insertTable',
    {
      label: 'Insert',
      icon: 'plus',
      items: ['highlight', 'blockQuote', 'mediaEmbed', 'codeBlock'],
    },
    '|',
    'alignment',
    '|',
    'bulletedList',
    'numberedList',
  ],
}

export { ClassicEditor, InlineEditor }
